/* fizmo_compat.c - Compatibility stubs for building fizmo.
 *
 * Provides hyphenation pattern stubs (normally generated by pattern_setup tool).
 * Locale data is now generated in libfizmo/src/locales/locale_data.c.
 */

#include <stddef.h>
#include <stdint.h>

#include <tools/types.h>
#include <tools/stringmap.h>

/* Stub for hyph_patterns - normally generated by pattern_setup tool */
#define hyph_patterns_c_INCLUDED

stringmap *pattern_map = NULL;

void init_patterns(void) {
  /* No hyphenation patterns compiled in */
}

int cmp_pattern(z_ucs *s1, z_ucs *s2) {
  while (*s1 && *s1 == *s2) { s1++; s2++; }
  return *s1 - *s2;
}
